name: 'combustivel_brasil'
version: '1.0.0'

profile: 'combustivel_brasil'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  combustivel_brasil:
    staging:
      schema: staging
      materialized: view
      tags: ['staging']

    intermediate:
      materialized: ephemeral
      tags: ['intermediate']

    marts:
      schema: marts
      materialized: table
      tags: ['marts']

seeds:
  combustivel_brasil:
    +schema: raw
    tags: ['seeds']

snapshots:
  combustivel_brasil:
    schema: snapshots
    tags: ['snapshots']
    
